sudo: required
services:
  - docker
 
before_install:
  - docker build -t davidfstevens/insight-test -f Dockerfile.dev .

script:
  - docker run davidfstevens/insight-test npm run test -- --coverage


